export enum ErrorCode {
  NETWORK_TIMEOUT = 'NET_001',
  STORAGE_QUOTA_EXCEEDED = 'STR_001',
  CLOUDINARY_QUOTA_EXCEEDED = 'STR_002',
  INVALID_IMAGE_FORMAT = 'IMG_001',
  IMAGE_TOO_LARGE = 'IMG_002',
  PERMISSION_DENIED = 'PRM_001',
  DATA_CORRUPTION = 'DAT_001',
  UNKNOWN_ERROR = 'UNK_001'
}
